version: 2
general: 
  branches:
    only:
      - master
      - /Feature1-.*/
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      # - run: docker ps -a
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run : yarn test
      - run : yarn lint
      - run : yarn lintfix
  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |  # this command is framework-dependent and may vary
            heroku git:remote -a sapient-team-1
            git push --force https://heroku:ba0067de-4423-4f73-9df6-7d756fce16a3@git.heroku.com/sapient-team-1.git HEAD:refs/heads/master
            sleep 5  # sleep for 5 seconds to wait for dynos
            heroku restart
- workflows:
    version: 2
    build-deploy:
      jobs:
        - build-job
        - deploy-jobs:  # only deploy when master successfully builds
            requires:
              - build-job
            filters:
              branches:
                only: master